// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/eleven-sh/hetzner-cloud-provider/service (interfaces: UserConfigResolver)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	userconfig "github.com/eleven-sh/hetzner-cloud-provider/userconfig"
	gomock "github.com/golang/mock/gomock"
)

// UserConfigResolver is a mock of UserConfigResolver interface.
type UserConfigResolver struct {
	ctrl     *gomock.Controller
	recorder *UserConfigResolverMockRecorder
}

// UserConfigResolverMockRecorder is the mock recorder for UserConfigResolver.
type UserConfigResolverMockRecorder struct {
	mock *UserConfigResolver
}

// NewUserConfigResolver creates a new mock instance.
func NewUserConfigResolver(ctrl *gomock.Controller) *UserConfigResolver {
	mock := &UserConfigResolver{ctrl: ctrl}
	mock.recorder = &UserConfigResolverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *UserConfigResolver) EXPECT() *UserConfigResolverMockRecorder {
	return m.recorder
}

// Resolve mocks base method.
func (m *UserConfigResolver) Resolve() (*userconfig.Config, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Resolve")
	ret0, _ := ret[0].(*userconfig.Config)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Resolve indicates an expected call of Resolve.
func (mr *UserConfigResolverMockRecorder) Resolve() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Resolve", reflect.TypeOf((*UserConfigResolver)(nil).Resolve))
}
